sudo: false
language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin

install:
  - env
  - pip install -r requirements/test.txt
  - pip install coveralls
  - python setup.py bdist_egg
  
# command to run tests
script: nosetests

after_success:
    - coveralls


