sudo: false
language: python
python:
  - "2.7"
  
matrix:
  include:
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.5.3
      # env: JYTHON=org.python:jython-installer:2.5.3 FOO=foo

before_install:
  - if [ -n "$JYTHON" ]; then ./before_install_jython.sh; source $HOME/myvirtualenv/bin/activate ;fi
  - if [ -n "$JYTHON" ]; then pip install jip==0.7; fi
  - if [ -n "$JYTHON" ]; then jip install joda-time:joda-time:2.3; fi
  - if [ -n "$JYTHON" ]; then export CLASSPATH=$VIRTUAL_ENV/javalib/*; fi
  - pip install unittest2
  
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin

install:
  - env
  - pip install -r requirements/test.txt
  - pip install coveralls
  - python setup.py bdist_egg
  
# command to run tests
script: nosetests

after_success:
    - coveralls


